In [ ]:
import tensorflow as tf
T = tf.constant([[1, 2, 3]])
T = tf.cast(T, dtype=tf.int32)
T

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [ ]:
T @ tf.transpose(T)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [ ]:
tensor_1 = tf.constant([[40, 50, 6],
                        [45, 78, 96],
                        [100, 33, 85]])

In [ ]:
print(tf.reduce_min(tensor_1))
print(tf.reduce_max(tensor_1))
print(tf.reduce_mean(tensor_1))
print(tf.reduce_sum(tensor_1))
print(tf.math.reduce_std(tf.cast(tensor_1, dtype=tf.float32)))
print(tf.math.reduce_variance(tf.cast(tensor_1, dtype=tf.float32)))

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(100, shape=(), dtype=int32)
tf.Tensor(59, shape=(), dtype=int32)
tf.Tensor(533, shape=(), dtype=int32)
tf.Tensor(30.2022, shape=(), dtype=float32)
tf.Tensor(912.17285, shape=(), dtype=float32)


In [ ]:
tensor_2 = tf.random.uniform(shape=(50, 2))
tensor_2

<tf.Tensor: shape=(50, 2), dtype=float32, numpy=
array([[0.35169005, 0.25782406],
       [0.36725032, 0.11282921],
       [0.6192653 , 0.11753368],
       [0.38260376, 0.8502444 ],
       [0.261047  , 0.2580285 ],
       [0.68390405, 0.02328908],
       [0.603199  , 0.63503206],
       [0.47367692, 0.6719345 ],
       [0.42320788, 0.5612483 ],
       [0.1543864 , 0.72589505],
       [0.62271845, 0.19921613],
       [0.01112282, 0.03979659],
       [0.06977391, 0.152529  ],
       [0.92617404, 0.5839906 ],
       [0.60112345, 0.76334333],
       [0.5609244 , 0.9806534 ],
       [0.23866093, 0.25578701],
       [0.26028085, 0.9756721 ],
       [0.5769657 , 0.9184153 ],
       [0.91871834, 0.02222216],
       [0.7828512 , 0.62789047],
       [0.2814443 , 0.18442488],
       [0.7024684 , 0.8145441 ],
       [0.16381896, 0.86950934],
       [0.9150727 , 0.10813081],
       [0.23842001, 0.9424672 ],
       [0.6068828 , 0.9134997 ],
       [0.65313256, 0.11018252],
       [0.1636504 , 0.09073

In [ ]:
tf.argmax(tensor_2)


<tf.Tensor: shape=(2,), dtype=int64, numpy=array([13, 15])>

In [ ]:
tf.reduce_max(tensor_2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9806534>

In [ ]:
tensor_2[29][0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.14301538>

In [ ]:
list = [0, 1 , 2, 3]
tf.one_hot(list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(list, depth=4, on_value="hmmm", off_value="fuck")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hmmm', b'fuck', b'fuck', b'fuck'],
       [b'fuck', b'hmmm', b'fuck', b'fuck'],
       [b'fuck', b'fuck', b'hmmm', b'fuck'],
       [b'fuck', b'fuck', b'fuck', b'hmmm']], dtype=object)>

In [ ]:
price_milk_petrol = tf.constant([[22, 105]])
price_milk_petrol.shape

TensorShape([1, 2])

In [ ]:
expence_two_weeks = tf.constant([[1, 0, 2, 0, 2, 1, 1],
                                [0, 0, 2, 0, 2, 0, 0]])
expence_two_weeks.shape

TensorShape([2, 7])

In [ ]:
tf.reduce_sum(price_milk_petrol @ expence_two_weeks)

<tf.Tensor: shape=(), dtype=int32, numpy=574>